server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dagong_survive?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: dagong
    password: dagong
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 2000ms

app:
  store: redis
